sudo: true
language: haskell

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

ghc:
- 8.6.5
- 8.4.4
- 8.2.2
- 8.0.2
- 7.10.3
- 7.8.4
- 7.6.3
- 7.4.2
- 7.0.4

install:
  - cabal update
  - cabal build

script:
  - echo 'No tests'

notifications:
  email: false
